version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: diego
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: diegoDB
    ports:
      - "5432:5432"
#     volumes:
#       - johnb:/var/lib/postgresql/data

# volumes:
#   johnb:

